### ISSUE TITLE
I like the idea

### ISSUE THREAD

**Issue by schmurfy** [ascaridol/mruby-flotte#1]
I am curious if you got anywhere with this :)

(sorry for using issues but since github no longer have pm and your profile does not include your email the choices are limited)

**Comment by Asmod4n** [comment]
This is the next bigger thing on my personal agenda, it will most likely be based upon my actor implemenatation and lmdb as log storage. I am also Asmod4n on Twitter :)

**Comment by Asmod4n** [comment]
@schmurfy decided to push the code as i come up with it to the repo.
Guess ill have to write a finite state machine gem, https://github.com/UniTN-Mechatronics/mruby-fsm isn't really what i am looking for, https://github.com/celluloid/celluloid-fsm looks more like it.

**Comment by schmurfy** [comment]
thanks for the ping :)

**Comment by Asmod4n** [comment]
@schmurfy got basic functionality working, now its cleanup time and testing testing testing.. :)
